# Generated by Django 5.2.9 on 2026-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_weekdaysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('eyes_away_time', models.IntegerField(default=0)),
                ('multiple_person_time', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
            ],
        ),
    ]
